# Generated by Django 4.2.5 on 2023-10-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
    ]
