# Generated by Django 4.2.5 on 2023-10-17 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Contenido'),
        ),
    ]
