# Generated by Django 4.2.5 on 2023-10-04 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 21, 35, 12, 798521, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
